### ISSUE TITLE
i am a card

### ISSUE THREAD

**Issue by ntwong0** [SJSURoboticsTeam/urc-autonomy-subsystem-2021#1]

**Comment by ntwong0** [comment]
add comments, pictures, etc

**Comment by kammce** [comment]
Attempt to reference another issue from this card: SJSURoboticsTeam/ControlSystems2021#1

**Comment by kammce** [comment]
Looks like that worked:

- [ ] First issue: SJSURoboticsTeam/ControlSystems2021#1
- [ ] Second issue: SJSURoboticsTeam/ControlSystems2021#4
- [ ] Third issue: SJSURoboticsTeam/ControlSystems2021#3
